<?php
$router->define([
    ''=>'src/signup/entry-point.php',
    'start'=>'src/index.php',
    'post'=>'src/post.php',
    'regist'=>'src/signup/regist.php',
    'check'=>'src/signup/check.php',
    'sign-up'=>'src/signup/sign-up.php',
    'log-in'=>'src/signup/log-in.php'
]);
