<?php
$router->define([
	''=>'src/signup/entryPoint.php',
	'start'=>'src/index.php',
    'post'=>'src/post.php',
    'regist'=>'src/signup/regist.php',
    'check'=>'src/signup/check.php',
    'signUp'=>'src/signup/signUp.php',
    'logIn'=>'src/signup/logIn.php'
]);
